// 版权所有 (C)2025, Simon·Richard
// 完成时间: 2025.12.4 16:31
// 这个 .proto 文件是 给 GoCache 这个分布式缓存系统定义 RPC 接口和数据格式的规范文件，用来让 gRPC 生成跨进程、跨语言的访问代码

// 使用 proto3 语法

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: pb/gdc.proto

// 包名

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// message 可以理解成“跨语言的 struct 定义”
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_pb_gdc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gdc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_pb_gdc_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Request) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Request) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ResponseForGet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseForGet) Reset() {
	*x = ResponseForGet{}
	mi := &file_pb_gdc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseForGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseForGet) ProtoMessage() {}

func (x *ResponseForGet) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gdc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseForGet.ProtoReflect.Descriptor instead.
func (*ResponseForGet) Descriptor() ([]byte, []int) {
	return file_pb_gdc_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseForGet) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ResponseForDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         bool                   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseForDelete) Reset() {
	*x = ResponseForDelete{}
	mi := &file_pb_gdc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseForDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseForDelete) ProtoMessage() {}

func (x *ResponseForDelete) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gdc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseForDelete.ProtoReflect.Descriptor instead.
func (*ResponseForDelete) Descriptor() ([]byte, []int) {
	return file_pb_gdc_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseForDelete) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

var File_pb_gdc_proto protoreflect.FileDescriptor

const file_pb_gdc_proto_rawDesc = "" +
	"\n" +
	"\fpb/gdc.proto\x12\x02pb\"G\n" +
	"\aRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"&\n" +
	"\x0eResponseForGet\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\")\n" +
	"\x11ResponseForDelete\x12\x14\n" +
	"\x05value\x18\x01 \x01(\bR\x05value2\x87\x01\n" +
	"\aGoCache\x12&\n" +
	"\x03Get\x12\v.pb.Request\x1a\x12.pb.ResponseForGet\x12&\n" +
	"\x03Set\x12\v.pb.Request\x1a\x12.pb.ResponseForGet\x12,\n" +
	"\x06Delete\x12\v.pb.Request\x1a\x15.pb.ResponseForDeleteB\x04Z\x02./b\x06proto3"

var (
	file_pb_gdc_proto_rawDescOnce sync.Once
	file_pb_gdc_proto_rawDescData []byte
)

func file_pb_gdc_proto_rawDescGZIP() []byte {
	file_pb_gdc_proto_rawDescOnce.Do(func() {
		file_pb_gdc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_gdc_proto_rawDesc), len(file_pb_gdc_proto_rawDesc)))
	})
	return file_pb_gdc_proto_rawDescData
}

var file_pb_gdc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_gdc_proto_goTypes = []any{
	(*Request)(nil),           // 0: pb.Request
	(*ResponseForGet)(nil),    // 1: pb.ResponseForGet
	(*ResponseForDelete)(nil), // 2: pb.ResponseForDelete
}
var file_pb_gdc_proto_depIdxs = []int32{
	0, // 0: pb.GoCache.Get:input_type -> pb.Request
	0, // 1: pb.GoCache.Set:input_type -> pb.Request
	0, // 2: pb.GoCache.Delete:input_type -> pb.Request
	1, // 3: pb.GoCache.Get:output_type -> pb.ResponseForGet
	1, // 4: pb.GoCache.Set:output_type -> pb.ResponseForGet
	2, // 5: pb.GoCache.Delete:output_type -> pb.ResponseForDelete
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_gdc_proto_init() }
func file_pb_gdc_proto_init() {
	if File_pb_gdc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_gdc_proto_rawDesc), len(file_pb_gdc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_gdc_proto_goTypes,
		DependencyIndexes: file_pb_gdc_proto_depIdxs,
		MessageInfos:      file_pb_gdc_proto_msgTypes,
	}.Build()
	File_pb_gdc_proto = out.File
	file_pb_gdc_proto_goTypes = nil
	file_pb_gdc_proto_depIdxs = nil
}
